version: '3.8'

services:
  node:
    container_name: bonsay_front
    restart: unless-stopped
    tty: true
    build: ./
    env_file:
      - .env
    networks:
      - bonsay
networks:
  bonsay:
    external: true
