version: '3.8'

services:
  node:
    container_name: bonsay_front
    restart: unless-stopped
    tty: true
    build: ./
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - bonsay
networks:
  bonsay:
    external: true
